require("config.lazy")
require("config.remap")
require("config.options")
require("config.lsp")
vim.lsp.log.set_level("ERROR")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("ts_ls")
vim.lsp.enable("cssls")
